version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mbl_db'
      MYSQL_USER: 'mbladmin'
      MYSQL_PASSWORD: 'mbltest'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mbl-mysql-data:/var/lib/mysql

volumes:
  mbl-mysql-data: